version: '3'
services:
  web:
     build: .
     ports:
       - "8001:80"
     links:
       - db
     volumes:
       - ./web:/var/www/html
  db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./db:/docker-entrypoint-initdb.d
